# Generated by Django 5.0.4 on 2024-05-13 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LockBoxApp", "0004_encryptedfilemodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EncryptedFileModel",
        ),
    ]
