# Generated by Django 5.0.4 on 2024-05-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LockBoxApp", "0005_delete_encryptedfilemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncryptedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=1024)),
                ("access_key", models.CharField(max_length=1024)),
            ],
        ),
    ]
